### ISSUE TITLE
auto import not triggering

### ISSUE THREAD

**Issue by pyyding** [dpzxsm/react-proptypes#1]
When pressing `shift + cmd + alt + P ` shortcut, `prop-types` wont be imported. 

Otherwise works pretty well and helps me ease some manual work, thanks :+1

**Comment by dpzxsm** [comment]
@pyyding This is my mistake. I forgot to develop it. I will add it in the next few days.

**Comment by dpzxsm** [comment]
@pyyding I've fixed the problem. If you feel it is useful, I really like you can star it and recommend more people to use it.

**Comment by pyyding** [comment]
thanks! Will do 👍
