### ISSUE TITLE
Support for shape?

### ISSUE THREAD

**Issue by AoDev** [dpzxsm/react-proptypes#10]
Hello, nice project you have here :)

I was wondering if it supports `PropTypes.shape({})` or I am doing something wrong?

Example:

```js
export default function Admin (props) {
  const user = props.user
  const name = user.name
}
```
would generate:
```js
Admin.propTypes = {
  user: PropTypes.shape({
    name: PropTypes.any
  })
}
```

**Comment by dpzxsm** [comment]
Not Support `shape`, because I don't know if anyone needs it, maybe someone like`object` or `any` Type.

This is a good idea, I have tried it before, but sometime there may be some interference.

Example:
``` javascript
export default function Admin (props) {
  const data = props.data; // Array Type
  const length = data.length;
}
```
would generate:
``` javascript
Admin.propTypes = {
  data: PropTypes.shape({
    length: PropTypes.any
  })
}
```

So, I must exclude all the properties of ` Basic Type`. Of course also includes Function's properties like `name` or  Array's properties like `length`.
But `name` and `length` is very common, isn't it?

**Comment by AoDev** [comment]
@dpzxsm I think your example above is totally ok. The component is using `length` to work, it is a valid case, so it does not matter if it's a builtin js property or a custom object.  Also it is much easier to remove that line if someone does not need it, than to add it manually.

I would definitely be interested in this, because I use Mobx, and my props are almost always objects with observable properties. So right now, it does not generate anything but the object name. We could also have two commands or settings if we want to keep two separate behaviours. Let me know if I can help. (It would really make my life easier :))

Edit: but you are right that there are these "interferences" like the array type.

**Comment by dpzxsm** [comment]
@AoDev  v1.5.0 has published. You can generate shape types by extension.

**Comment by AoDev** [comment]
@dpzxsm 

I have tried. Here is a small component:
```js
function SocialItem (props) {
  const socialLink = props.socialLink
  return (
    <div className="space-bottom-1">
      <div className="flex-row-center">
        <div className="flex-no-shrink">
          <Icon name={`#${socialLink.icon}`} color={socialLink.iconColor}/>
        </div>
        <h3 className="space-left-1">{socialLink.label}</h3>
      </div>
      <a
        className="truncate--inline width-100p"
        href={socialLink.link}
        target={socialLink.id !== 'contact_mail' ? 'blank' : null}>
        {socialLink.link}
      </a>
    </div>
  )
}
```
And it generates:

```js
SocialItem.propTypes = {
  socialLink: PropTypes.shape({})
}
```

Which is correct :) Cool
But, could we go at least one level deep? 

```js
SocialItem.propTypes = {
  socialLink: PropTypes.shape({
    icon: PropTypes.any,
    label: PropTypes.any,
    // ...
  })
}
```

**Comment by dpzxsm** [comment]
@AoDev  maybe hava  a bug，it should support.
Edit：I may have considered less cases, resulting in not getting the correct properties.I will fix this problem as soon as possible.

**Comment by dpzxsm** [comment]
@AoDev Has fixed in v1.5.2,  I rarely use vscode, so no such problems have been found. In addition, `shape` supports multiple level deep, enjoy it. If you have more problems, you can create more issues. You can recommend to more friends to use， It helps to improve the extension.

**Comment by AoDev** [comment]
@dpzxsm It's working and this is awesome : ) If you've have some BTC address, I'll tip ;)

**Comment by dpzxsm** [comment]
@AoDev No, thanks. It ’s enough to provide convenience for others.😊

**Comment by gboysko** [comment]
+1 to go one level deep into array. I know that this issue is closed, but wanted to express my support of it!

**Comment by gboysko** [comment]
FWIW, I am seeing it *not* working:

Desired is:

```
...
App.propTypes = {
    budgets: PropTypes.shape({
        items: PropTypes.arrayOf(
            PropTypes.shape({
                id: PropTypes.string.isRequired,
                name: PropTypes.string.isRequired,
            })
        ),
    }),
   listBudgetsFn: PropTypes.func,
}
```

but it generates:

```
...
App.propTypes = {
    budgets: PropTypes.shape({
        items: PropTypes.arrayOf(),
    }),
   listBudgetsFn: PropTypes.func,
}
```

**Comment by dpzxsm** [comment]
@gboysko  Currently, the extension does not support `arrayOf` type generation，but the previous PropType will be merged. Sometime，if other  PropTypet nested into `arrayOf` type , this will happen，Not just `shape` type.  I will fix it in next verison.
If you want support `arrayOf` Type, you can create new issuse.
