### ISSUE TITLE
Not supported for TypeScript (tsx) files?

### ISSUE THREAD

**Issue by scscgit** [dpzxsm/react-proptypes#11]
I've been unable to use this at all for .tsx files, which I've been able to reproduce by creating a simple project and being able to access the PropTypesGenerate Code Action from a .jsx file (or a key shortcut), yet this stopped working after renaming the file to .tsx. I didn't find this documented as an expected behavior anywhere, and I don't know about any other propTypes generator. Could you please notify users under Readme about the current situation?

To make sure this is covered in the context of use-cases, as far as I understand (based on articles like https://stackoverflow.com/questions/56056489/is-proptypes-become-obsolete-in-typescript-react), PropTypes are still relevant for TS code as a runtime check compared to a compile-time check. More specifically, in my .tsx files I'm still getting an eslint warning of `react/prop-types` when using eslint recommended settings if the function type is React.FC. However, it's interesting that this warning seems to disappear when I also strongly type the props like `({propName}: {propName: propType})` (which should be redundant when also using `FC<{propName: propType}>`, but this seems to remove the warning). However, I've also found that the FunctionComponent may be an anti-pattern altogether based on reasoning under https://stackoverflow.com/a/61547010, but I can't find any official guideline.

(By the way, is there any way to use command line to run the generation for all components under all files automatically? The description is too generic and doesn't contain examples.)

**Comment by dpzxsm** [comment]
@scscgit Now，the extension does not support TypeScript，because I think typescript doesn't need proptypes in most cases. you can use command line to generate PropTypes for one TypeScript File，I didn't adapt typescript completely，maybe have some bug, but It's useful in most cases.
Install command line tool by```npm install react-proptypes-generate -g``` and run```rpg-cli -h``` show help

**Comment by scscgit** [comment]
Well as I said, you could at least mention this lack of support in some visible places including Readme, because people are pretty much supposed to use TypeScript nowadays. I had to spend several days researching and debugging this tool before even coming to this conclusion, and there is literally no other alternative (when using tools like Visual Studio Code) for people who use eslint with FC in larger projects (that mix types even with libraries) where maintaining PropTypes by hand isn't feasible. But thanks to finding out that FC is an anti-pattern (as it doesn't support generics), I've come to the conclusion that I won't need to use this project after all, so it's probably enough to just document this reasoning and deprecating it for TS approach. (I still can't figure out how any new developer is supposed to realize the most current React best practices though, because every authority seems to be pushing a different approach; for example, reactjs.org tutorial doesn't even acknowledge the existence of functional components...)

So about the command line tool, there is no way to let it cover multiple files (the entire project) in any automated fashion, other than manually iterating over and copying all of the file names? That means Windows/Linux (cmd/shell) users will need to write their own scripts using `find .` or `for` without any help. By the way, I personally found the cli help description very ambiguous and lacking examples of use-cases, and I prefer npx over global npm install (where the version doesn't update to latest automatically) when composing scripts to be a part of any workflow (e.g. as npm run scripts); but that's just my opinion. Thanks for your time.

**Comment by dpzxsm** [comment]
@scscgit  You're right，I will support Typescript in vscode.  As for the command line，command line tools are not perfect because there are so few people using them, almost only myself.  Automatic recursion of all files and automatic identification of component names are possible. But the side effect is that it may take a long time because there is a lot of AST parsing. I don't have much free time now，I will implement these functions as soon as possible . Npx support is also under consideration.

**Comment by dpzxsm** [comment]
@scscgit  In v1.6.0 ， Fixed it
