### ISSUE TITLE
Setting for isRequired

### ISSUE THREAD

**Issue by piersolenski** [dpzxsm/react-proptypes#15]
90% of the time I'm manually adding `isRequired` to the end of generated Prop Types. A boolean setting to add this automatically would be great!

**Comment by dpzxsm** [comment]
@superfunkminister  It is really necessary.

**Comment by dpzxsm** [comment]
v1.6.1 has fixed it

**Comment by piersolenski** [comment]
Gotta love that speedy turnaround 🚀
