### ISSUE TITLE
feature: add support for destructured props / shape

### ISSUE THREAD

**Issue by AoDev** [dpzxsm/react-proptypes#16]
The extension works great but does not handle object destructuring syntax.  
Is this something we could add?

For example, this will generate proptypes properly:

```js
function MyComponent ({someShape}) {
  const prop1 = someShape.prop1
  const prop2 = someShape.prop2
  return (
    <div>{prop1} {prop2}</div>
  )
}

// Generates
MyComponent.propTypes = {
  someShape: PropTypes.shape({
    prop1: PropTypes.any,
    prop2: PropTypes.any
  })
}
```

But the same code using destructuring, will not:

```js
function MyComponent ({someShape}) {
  const {prop1, prop2} = someShape
  return (
    <div>{prop1} {prop2}</div>
  )
}

// Generates
MyComponent.propTypes = {
  someShape: PropTypes.any
}
```

**Comment by dpzxsm** [comment]
@AoDev  
Currently, I only deconstruct root props，but not shape，because it will cause a lot of recursion. 
I will try to see if there is a performance problem first, if not, I will fix it as soon as possible.

**Comment by AoDev** [comment]
In the example above, they have the same level of nesting. It's only the destructuring syntax that seems to be an issue.

**Comment by dpzxsm** [comment]
@AoDev v1.6.2 has published

**Comment by AoDev** [comment]
@dpzxsm Awesome, thanks for being so fast
