### ISSUE TITLE
Interleaved comments discarded

### ISSUE THREAD

**Issue by ivanvaccari** [dpzxsm/react-proptypes#18]
I'm using this extension quite for a while now, and i'm used to add comments interleaved to proptypes to define what they do.
But when i need to update propTypes, the extension recreate the structure by merging the old one discarding comments.

TO REPRODUCE:
- Create a simple component and add a prop.
- Use the extension to generate propTypes
- Add a comment in the generated propTypes structure
- regenerate the props using the extension
- the comment is lost.

It would be very nice if the merge also keeps the comments.

**Comment by dpzxsm** [comment]
@grisson2 Good idea , There's a way to keep comments,  but there must be strict format requirements, the comment must be on the same line as a PropType;

Like:

```javascript
Audio.propTypes = {
  src: PropTypes.any, // the audio's source
  style: PropTypes.shape({
    color: PropTypes.string,
    fontSize: PropTypes.any
  }) // the audio's style
};
```
Proptypes that do not conform to this format will still lose comments
I will add it in next version

**Comment by dpzxsm** [comment]
@grisson2  I have found a way to add commets for proptypes, can you provide the example code with comments ?

**Comment by ivanvaccari** [comment]
Hi. 
Something like this?

```
static propTypes = {
        onClick: PropTypes.func,
        text: PropTypes.string,
        icon: PropTypes.string, // font awesome icon to be displayed. If unset nothig is displayed
        value: PropTypes.any,  // some value passed back on click
        source: PropTypes.any,  // some value passed back on click as 2nd parameter
        className: PropTypes.string,  // css classes to be applied to the item
        type: PropTypes.string, // set the rendered item type: "placeholder" make it just a displayed text, "link" (default) make a clickable item
    }
```

**Comment by dpzxsm** [comment]
@grisson2  Yes，Thanks.

**Comment by dpzxsm** [comment]
@vaccariv  v1.7.0 has fixed it. click [keep-proptypess-comments](https://github.com/dpzxsm/react-proptypes-generate#keep-proptypess-comments) to know more about it.

**Comment by ivanvaccari** [comment]
@dpzxsm Nice, thanks! I will try soon.
