### ISSUE TITLE
custom mapping

### ISSUE THREAD

**Issue by ShaneZhengNZ** [dpzxsm/react-proptypes#2]
If a prop defaults to noop, at the moment it generates PropTypes.any, this is good.

But, I would suggest that we can customize it, for example, since we always default function props to noop, such as 
```javascript
onChange: _noop,
```
I would like to generate `onChange: PropTypes.func` instead of `onChange: PropTypes.any`

Effectively, I want to map `_noop` to `PropTypes.func`. Is that possible?

**Comment by dpzxsm** [comment]
@ShaneZhengNZ  If you’re component have  `_noop ` defaultProps ,it will generate PropTypes.func, like this:
```
  class Test extends Component{
     static defaultProps = {
        onChange: () => {}
     }
  }
  // or
  Test.defaultProps = {
     onChange: () => {}
  }
```
I don't know if I misunderstood it or not , Is you wan't  get `() => {}` an alias for `_noop` ? Do  you want write like that：
```
 Test.defaultProps = {
     onChange:_noop
  }
```
and generate `onChange: PropTypes.func` ?

**Comment by dpzxsm** [comment]
Close it because long time no response.
