### ISSUE TITLE
How to avoid generated proptypes getting sorted?

### ISSUE THREAD

**Issue by kawpii** [dpzxsm/react-proptypes#24]
Thanks for the extension!

If I generate prop types for the following component using 

```
export default function CompName({ e, b, u, i, a }) {
  return (
   ...
  );
}
```

generated proptypes are sorted in alphabetical order.

```
CompName.propTypes = {
   a : PropTypes.string.isRequired,
  b : PropTypes.string.isRequired,
  e : PropTypes.string.isRequired,
  i : PropTypes.string.isRequired,
  u : PropTypes.string.isRequired,
};

```

How to avoid this behavior?

**Comment by dpzxsm** [comment]
@kaushalyap Now the default is sorted. If you don't need it, I can put forward more options

**Comment by kawpii** [comment]
@dpzxsm Yes please do so.

**Comment by dpzxsm** [comment]
v1.7.6 has fixed it

**Comment by dpzxsm** [comment]
@kaushalyap  v1.7.6 has fixed it

**Comment by kawpii** [comment]
Thanks!
