### ISSUE TITLE
How to change the config ?

### ISSUE THREAD

**Issue by capucineSoum** [dpzxsm/react-proptypes#27]
Hello,

Thank you for this extension ! 

I have a question. I couldn't find a way to change the configuration. I saw in the documentation that I needed to create a rpg.config.json file at the root. I am not sure at which root. I tried to add it at the route of the project but It didn't work. 
I also tried to add it in the same folder than the settings.json of VSCode config (C:\Users\_username_\AppData\Roaming\Code\User).

Here is the content of the file :
```
 {
    "autoImport": "ES6",
    "codeStyle": "default",
    "noMergeOld": false,
    "mergeOldIfExist": true,
    "noShape": false,
    "tabWidth": 2,
    "quote": "double",
    "trailingComma": false,
    "semicolon": true,
    "arrayLike": true,
    "isRequired": true,
    "include": [
      "src/**/*" 
    ],
    "exclude": [
      "node_modules"
    ]
  }
```

I am using VSCode on Windows.

Thank you

**Comment by dpzxsm** [comment]
@capucineSoum  rpg.config.json is only use in  the Comannd Line,  If you just use vscode，it should be Setting->Extensions->ReactPropType configuration.
<img width="1098" alt="image" src="https://user-images.githubusercontent.com/20736977/174923416-0b2608f2-4af5-4435-896d-df879364a746.png">

**Comment by capucineSoum** [comment]
Thank you @dpzxsm !
