### ISSUE TITLE
Not working on pure function components

### ISSUE THREAD

**Issue by GianfrancoCorrea** [dpzxsm/react-proptypes#3]
Selecting name of function it say: 

> the selected text is not a valid react component

and i need propTypes anyway.

` `
`import React from 'react';`

`function Audio(props) {`
   `const clip  = props.clip;`
    `return (`
        `<div className="player">`
      `  </div>`
  `  );`
`}`
` `
`export default Audio;`

**Comment by dpzxsm** [comment]
@GianfrancoCorrea  Oh！I will fix it
