### ISSUE TITLE
Not working on functional components made with arrow function

### ISSUE THREAD

**Issue by ARajic** [dpzxsm/react-proptypes#4]
Not working with functional components

const THeaders = props => (
  // some JSX code
);

Error: The selected text is not a valid React Component !

**Comment by dpzxsm** [comment]
@ARajic I'll fix it, thanks!

**Comment by dpzxsm** [comment]
I has fixed it, see this commit [Support Pure ArrowFunction Component](https://github.com/dpzxsm/react-proptypes-generate/commit/6fd7f87fc2ee883a7ff2b7526a6a8485d25890f1)

**Comment by antrtr** [comment]
Not work for Class Component as well
