### ISSUE TITLE
Indentation

### ISSUE THREAD

**Issue by mcelkys** [dpzxsm/react-proptypes#9]
Is there a way to configure the number of spaces that are used for indentation in the generated code? If not, can said configuration option be added? 

Ideally it would just detect whatever your default setting in VSCode is and just use that, but any configuration would be appreciated.

**Comment by dpzxsm** [comment]
@mcelkys  Sorry, I haven’t seen this issue until now. It is a good issue.  This extension is base `recast`,  so add it is easy.  I will take the time to add some configuration like [options](https://github.com/benjamn/recast/blob/master/lib/options.ts). Thank you for supporting my extension.

**Comment by dpzxsm** [comment]
@mcelkys  `v1.4.0` already published.

**Comment by mcelkys** [comment]
Thank you for your response! I've updated to the latest version and I am now able to configure indentations. Thank you!
